Form connection
monicapajon/moviesApp-react pull request #7
Opened 2023-03-08 02:35 UTC by monicapajon

Downloaded the axios and react-hook-form libraries. Created Register User Form and connected to Firebase

2023-03-13 01:46 UTC, adrianmdp requested changes

2023-03-13 01:46 UTC, adrianmdp commented on src/components/forms/AddCategory/index.tsx
> +const AddCategory = () => {
Por que hay un AddCategory?

2023-03-13 01:46 UTC, adrianmdp commented on src/components/layout/Aside/index.tsx
> +const Aside = () => {
Tampoco teníamos aside

2023-03-13 01:46 UTC, adrianmdp commented on src/components/layout/Navbar/index.tsx
> +                        <NavLink className="nav-link" to="/categories">Categorías</NavLink>
No tenemos esta pagina.

2023-03-13 01:46 UTC, adrianmdp commented on src/components/layout/Navbar/index.tsx
> +                        <NavLink className="nav-link" to="/users">Usuarios</NavLink>
No tenemos esta pagina tampoco.

2023-03-13 01:46 UTC, adrianmdp commented on src/pages/categories/index.tsx
> +const Categories = () => {
No se pide esta pagina.

2023-03-13 01:46 UTC, adrianmdp commented on src/pages/users/index.tsx
> +const Users = () => {
No se pide esta pagina

2023-03-13 01:46 UTC, adrianmdp requested changes

2023-03-13 01:46 UTC, adrianmdp commented on src/App.tsx
> +                <Route path="/users" element={<Users />} />
Borrar

2023-03-13 01:46 UTC, adrianmdp commented on src/App.tsx
> +                <Route path="/categories" element={<Categories />} />
Borrar

2023-03-15 22:01 UTC, monicapajon commented on src/components/forms/AddCategory/index.tsx
> +const AddCategory = () => {
Estaba practicando y lo subí al repo sin querer. Archivo eliminado

2023-03-15 22:24 UTC, monicapajon commented on src/components/layout/Navbar/index.tsx
> +                        <NavLink className="nav-link" to="/users">Usuarios</NavLink>
Página eliminada

2023-03-15 22:25 UTC, monicapajon commented on src/pages/users/index.tsx
> +const Users = () => {
Página eliminada

2023-03-15 23:15 UTC, monicapajon commented on src/App.tsx
> +                <Route path="/users" element={<Users />} />
Se borró

2023-03-15 23:15 UTC, monicapajon commented on src/App.tsx
> +                <Route path="/categories" element={<Categories />} />
Se borró

2023-03-26 23:27 UTC, adrianmdp requested changes

2023-03-26 23:27 UTC, adrianmdp commented on src/components/forms/AddCategory/index.tsx
> +const AddCategory = () => {
Si lo eliminás no debería volver a aparecer en la PR

2023-03-26 23:27 UTC, adrianmdp commented on src/components/layout/Aside/index.tsx
> +const Aside = () => {
Falta eliminar!

2023-03-26 23:27 UTC, adrianmdp commented on src/components/layout/Navbar/index.tsx
> +                        <NavLink className="nav-link" to="/users">Usuarios</NavLink>
Eliminar y volver a subir los cambios.

2023-03-26 23:27 UTC, adrianmdp commented on src/components/layout/Navbar/index.tsx
> +                        <NavLink className="nav-link" to="/categories">Categorías</NavLink>
Eliminar y volver a subir los cambios!

2023-03-26 23:27 UTC, adrianmdp commented on src/pages/categories/index.tsx
> +const Categories = () => {
Falta eliminar.

2023-03-26 23:27 UTC, adrianmdp commented on src/pages/users/index.tsx
> +const Users = () => {
Lo mismo aca

2023-03-27 03:05 UTC, adrianmdp approved these changes

2023-03-27 03:12 UTC, merged